name: Laravel Feature Tests ğŸ§ª

on:
#   push:
#     branches: [ main ]
    workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Docker containers ğŸ³
        run: |
          export DISABLE_LOGGING=true
          docker compose -f docker-compose.yml up -d

      - name: Sleep â±ï¸
        run: sleep 30s

      - name: Install composer dependencies ğŸ“¦
        run: docker compose exec -T laravel-api composer install

      - name: Check PHPUnit binary ğŸ”
        run: docker compose exec -T laravel-api ls -la /var/www/vendor/bin

      - name: Migrate & seed database ğŸŒ±
        run: docker compose exec -T laravel-api php artisan migrate:refresh --seed

      - name: Run Laravel Feature tests ğŸ§ª
        run: |
          docker compose exec -T laravel-api ./vendor/bin/phpunit --testdox --colors=always /var/www/tests/Feature
